name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Branch name
        run: pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        run: echo "pull number = $pull_number"
